acme_main:
    resource: "@AcmeMainBundle/Controller/"
    type:     annotation
    prefix:   /

_welcome:
    pattern:  /
    defaults: { _controller: AcmeMainBundle:Default:index }

register:
    pattern:  /register
    defaults: { _controller: AcmeMainBundle:Security:register }

login:
    pattern: /login
    defaults: { _controller: AcmeMainBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout
